name: tests

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'python/**'
      - '.github/workflows/tests.yml'
  push:
    branches: [ master ]
    paths:
      - 'python/**'
      - '.github/workflows/tests.yml'

jobs:
  pytest:
    name: pytest (py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('python/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-

      - name: Install deps
        working-directory: python
        env:
          PYTHONPATH: ${{ github.workspace }}/python
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov typer

      - name: Run tests (pytest)
        working-directory: python
        env:
          PYTHONPATH: ${{ github.workspace }}/python
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=amount_partition --cov-report=xml

      - name: Upload coverage (artifact)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: python/coverage.xml

      - name: CLI E2E (bash)
        working-directory: python
        env:
          PYTHONPATH: ${{ github.workspace }}/python
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq
          chmod +x tests/cli_e2e.sh
          tests/cli_e2e.sh
