name: tests

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'python/**'
      - '.github/workflows/tests.yml'
  push:
    branches: [ master ]
    paths:
      - 'python/**'
      - '.github/workflows/tests.yml'

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        working-directory: python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        working-directory: python
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=amount_partition --cov-report=xml

      - name: Upload coverage (optional)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: python/coverage.xml
